-- 2021-05-07
-- 관리자접속

CREATE TABLESPACE nonghyupDB
DATAFILE 'C:/oraclexe/data/nonghyupDB.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K ;

CREATE USER nhuser IDENTIFIED BY nhuser
DEFAULT TABLESPACE nonghyupDB ;

GRANT DBA TO nhuser ;